=begin
#Akeyless API

#The purpose of this application is to provide access to Akeyless API.

The version of the OpenAPI document: 2.0
Contact: support@akeyless.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.5.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Akeyless::GatewayDownloadCustomerFragmentsOutput
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Akeyless::GatewayDownloadCustomerFragmentsOutput do
  let(:instance) { Akeyless::GatewayDownloadCustomerFragmentsOutput.new }

  describe 'test an instance of GatewayDownloadCustomerFragmentsOutput' do
    it 'should create an instance of GatewayDownloadCustomerFragmentsOutput' do
      expect(instance).to be_instance_of(Akeyless::GatewayDownloadCustomerFragmentsOutput)
    end
  end
  describe 'test attribute "cf_json"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
