=begin
#Akeyless API

#The purpose of this application is to provide access to Akeyless API.

The version of the OpenAPI document: 2.0
Contact: support@akeyless.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Akeyless::UscDeleteSecretOutput
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Akeyless::UscDeleteSecretOutput do
  let(:instance) { Akeyless::UscDeleteSecretOutput.new }

  describe 'test an instance of UscDeleteSecretOutput' do
    it 'should create an instance of UscDeleteSecretOutput' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Akeyless::UscDeleteSecretOutput)
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
