=begin
#Akeyless API

#The purpose of this application is to provide access to Akeyless API.

The version of the OpenAPI document: 2.0
Contact: support@akeyless.io
Generated by: https://openapi-generator.tech
Generator version: 7.9.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Akeyless::WebBastionGuacamole
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Akeyless::WebBastionGuacamole do
  let(:instance) { Akeyless::WebBastionGuacamole.new }

  describe 'test an instance of WebBastionGuacamole' do
    it 'should create an instance of WebBastionGuacamole' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Akeyless::WebBastionGuacamole)
    end
  end

  describe 'test attribute "keyboard_layout"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
