=begin
#Akeyless API

#The purpose of this application is to provide access to Akeyless API.

The version of the OpenAPI document: 2.0
Contact: support@akeyless.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.0-SNAPSHOT

=end

require 'date'
require 'time'

module Akeyless
  # gatewayUpdateMigration is a command that update migration
  class GatewayUpdateMigration
    attr_accessor :aws_key

    attr_accessor :aws_key_id

    attr_accessor :aws_region

    attr_accessor :azure_client_id

    attr_accessor :azure_kv_name

    attr_accessor :azure_secret

    attr_accessor :azure_tenant_id

    attr_accessor :hashi_json

    attr_accessor :hashi_ns

    attr_accessor :hashi_token

    attr_accessor :hashi_url

    attr_accessor :id

    # Migration name
    attr_accessor :name

    attr_accessor :protection_key

    attr_accessor :target_location

    # Authentication token (see `/auth` and `/configure`)
    attr_accessor :token

    attr_accessor :type

    # The universal identity token, Required only for universal_identity authentication
    attr_accessor :uid_token

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'aws_key' => :'aws-key',
        :'aws_key_id' => :'aws-key-id',
        :'aws_region' => :'aws-region',
        :'azure_client_id' => :'azure-client-id',
        :'azure_kv_name' => :'azure-kv-name',
        :'azure_secret' => :'azure-secret',
        :'azure_tenant_id' => :'azure-tenant-id',
        :'hashi_json' => :'hashi-json',
        :'hashi_ns' => :'hashi-ns',
        :'hashi_token' => :'hashi-token',
        :'hashi_url' => :'hashi-url',
        :'id' => :'id',
        :'name' => :'name',
        :'protection_key' => :'protection-key',
        :'target_location' => :'target-location',
        :'token' => :'token',
        :'type' => :'type',
        :'uid_token' => :'uid-token'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'aws_key' => :'String',
        :'aws_key_id' => :'String',
        :'aws_region' => :'String',
        :'azure_client_id' => :'String',
        :'azure_kv_name' => :'String',
        :'azure_secret' => :'String',
        :'azure_tenant_id' => :'String',
        :'hashi_json' => :'String',
        :'hashi_ns' => :'Array<String>',
        :'hashi_token' => :'String',
        :'hashi_url' => :'String',
        :'id' => :'String',
        :'name' => :'String',
        :'protection_key' => :'String',
        :'target_location' => :'String',
        :'token' => :'String',
        :'type' => :'String',
        :'uid_token' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Akeyless::GatewayUpdateMigration` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Akeyless::GatewayUpdateMigration`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'aws_key')
        self.aws_key = attributes[:'aws_key']
      end

      if attributes.key?(:'aws_key_id')
        self.aws_key_id = attributes[:'aws_key_id']
      end

      if attributes.key?(:'aws_region')
        self.aws_region = attributes[:'aws_region']
      end

      if attributes.key?(:'azure_client_id')
        self.azure_client_id = attributes[:'azure_client_id']
      end

      if attributes.key?(:'azure_kv_name')
        self.azure_kv_name = attributes[:'azure_kv_name']
      end

      if attributes.key?(:'azure_secret')
        self.azure_secret = attributes[:'azure_secret']
      end

      if attributes.key?(:'azure_tenant_id')
        self.azure_tenant_id = attributes[:'azure_tenant_id']
      end

      if attributes.key?(:'hashi_json')
        self.hashi_json = attributes[:'hashi_json']
      end

      if attributes.key?(:'hashi_ns')
        if (value = attributes[:'hashi_ns']).is_a?(Array)
          self.hashi_ns = value
        end
      end

      if attributes.key?(:'hashi_token')
        self.hashi_token = attributes[:'hashi_token']
      end

      if attributes.key?(:'hashi_url')
        self.hashi_url = attributes[:'hashi_url']
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'protection_key')
        self.protection_key = attributes[:'protection_key']
      end

      if attributes.key?(:'target_location')
        self.target_location = attributes[:'target_location']
      end

      if attributes.key?(:'token')
        self.token = attributes[:'token']
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      end

      if attributes.key?(:'uid_token')
        self.uid_token = attributes[:'uid_token']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @name.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          aws_key == o.aws_key &&
          aws_key_id == o.aws_key_id &&
          aws_region == o.aws_region &&
          azure_client_id == o.azure_client_id &&
          azure_kv_name == o.azure_kv_name &&
          azure_secret == o.azure_secret &&
          azure_tenant_id == o.azure_tenant_id &&
          hashi_json == o.hashi_json &&
          hashi_ns == o.hashi_ns &&
          hashi_token == o.hashi_token &&
          hashi_url == o.hashi_url &&
          id == o.id &&
          name == o.name &&
          protection_key == o.protection_key &&
          target_location == o.target_location &&
          token == o.token &&
          type == o.type &&
          uid_token == o.uid_token
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [aws_key, aws_key_id, aws_region, azure_client_id, azure_kv_name, azure_secret, azure_tenant_id, hashi_json, hashi_ns, hashi_token, hashi_url, id, name, protection_key, target_location, token, type, uid_token].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Akeyless.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
