=begin
#Akeyless API

#The purpose of this application is to provide access to Akeyless API.

The version of the OpenAPI document: 2.0
Contact: support@akeyless.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.4.0-SNAPSHOT

=end

require 'date'
require 'time'

module Akeyless
  class GeneralConfigPart
    # AkeylessUrl is here for BC only. Gator will still return it if it exists in the configuration, but new clients (>=2.34.0) will ignore it and override it with what exists in their local file. It will no longer be sent to Gator for update, so new clusters will only have the default value saved in the DB.
    attr_accessor :akeyless_url

    attr_accessor :api_token_ttl

    attr_accessor :display_name

    attr_accessor :enable_tls

    attr_accessor :enable_tls_configure

    attr_accessor :enable_tls_curl

    attr_accessor :enable_tls_hvp

    attr_accessor :gw_cluster_url

    attr_accessor :tcp_port

    attr_accessor :tls_cert

    attr_accessor :tls_key

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'akeyless_url' => :'akeyless_url',
        :'api_token_ttl' => :'api_token_ttl',
        :'display_name' => :'display_name',
        :'enable_tls' => :'enable_tls',
        :'enable_tls_configure' => :'enable_tls_configure',
        :'enable_tls_curl' => :'enable_tls_curl',
        :'enable_tls_hvp' => :'enable_tls_hvp',
        :'gw_cluster_url' => :'gw_cluster_url',
        :'tcp_port' => :'tcp_port',
        :'tls_cert' => :'tls_cert',
        :'tls_key' => :'tls_key'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'akeyless_url' => :'String',
        :'api_token_ttl' => :'String',
        :'display_name' => :'String',
        :'enable_tls' => :'Boolean',
        :'enable_tls_configure' => :'Boolean',
        :'enable_tls_curl' => :'Boolean',
        :'enable_tls_hvp' => :'Boolean',
        :'gw_cluster_url' => :'String',
        :'tcp_port' => :'String',
        :'tls_cert' => :'String',
        :'tls_key' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Akeyless::GeneralConfigPart` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Akeyless::GeneralConfigPart`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'akeyless_url')
        self.akeyless_url = attributes[:'akeyless_url']
      end

      if attributes.key?(:'api_token_ttl')
        self.api_token_ttl = attributes[:'api_token_ttl']
      end

      if attributes.key?(:'display_name')
        self.display_name = attributes[:'display_name']
      end

      if attributes.key?(:'enable_tls')
        self.enable_tls = attributes[:'enable_tls']
      end

      if attributes.key?(:'enable_tls_configure')
        self.enable_tls_configure = attributes[:'enable_tls_configure']
      end

      if attributes.key?(:'enable_tls_curl')
        self.enable_tls_curl = attributes[:'enable_tls_curl']
      end

      if attributes.key?(:'enable_tls_hvp')
        self.enable_tls_hvp = attributes[:'enable_tls_hvp']
      end

      if attributes.key?(:'gw_cluster_url')
        self.gw_cluster_url = attributes[:'gw_cluster_url']
      end

      if attributes.key?(:'tcp_port')
        self.tcp_port = attributes[:'tcp_port']
      end

      if attributes.key?(:'tls_cert')
        self.tls_cert = attributes[:'tls_cert']
      end

      if attributes.key?(:'tls_key')
        self.tls_key = attributes[:'tls_key']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          akeyless_url == o.akeyless_url &&
          api_token_ttl == o.api_token_ttl &&
          display_name == o.display_name &&
          enable_tls == o.enable_tls &&
          enable_tls_configure == o.enable_tls_configure &&
          enable_tls_curl == o.enable_tls_curl &&
          enable_tls_hvp == o.enable_tls_hvp &&
          gw_cluster_url == o.gw_cluster_url &&
          tcp_port == o.tcp_port &&
          tls_cert == o.tls_cert &&
          tls_key == o.tls_key
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [akeyless_url, api_token_ttl, display_name, enable_tls, enable_tls_configure, enable_tls_curl, enable_tls_hvp, gw_cluster_url, tcp_port, tls_cert, tls_key].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Akeyless.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
