=begin
#Akeyless API

#The purpose of this application is to provide access to Akeyless API.

The version of the OpenAPI document: 2.0
Contact: support@akeyless.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.1.0-SNAPSHOT

=end

require 'date'
require 'time'

module Akeyless
  class SignPKICertWithClassicKey
    # The common name to be included in the PKI certificate
    attr_accessor :common_name

    # A comma-separated list of the country that will be set in the issued certificate
    attr_accessor :country

    # The name of the key to use in the sign PKI Cert process
    attr_accessor :display_id

    # DNS Names to be included in the PKI certificate (in a comma-delimited list)
    attr_accessor :dns_names

    # key-usage
    attr_accessor :key_usage

    # A comma-separated list of the locality that will be set in the issued certificate
    attr_accessor :locality

    # A comma-separated list of organizational units (OU) that will be set in the issued certificate
    attr_accessor :organizational_units

    # A comma-separated list of organizations (O) that will be set in the issued certificate
    attr_accessor :organizations

    # A comma-separated list of the postal code that will be set in the issued certificate
    attr_accessor :postal_code

    # A comma-separated list of the province that will be set in the issued certificate
    attr_accessor :province

    # PublicKey using for signing in a PEM format.
    attr_accessor :public_key_pem_data

    # SigningMethod
    attr_accessor :signing_method

    # A comma-separated list of the street address that will be set in the issued certificate
    attr_accessor :street_address

    # Authentication token (see `/auth` and `/configure`)
    attr_accessor :token

    # he requested Time To Live for the certificate, in seconds
    attr_accessor :ttl

    # The universal identity token, Required only for universal_identity authentication
    attr_accessor :uid_token

    # The URI Subject Alternative Names to be included in the PKI certificate (in a comma-delimited list)
    attr_accessor :uri_sans

    # classic key version
    attr_accessor :version

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'common_name' => :'common-name',
        :'country' => :'country',
        :'display_id' => :'display-id',
        :'dns_names' => :'dns-names',
        :'key_usage' => :'key-usage',
        :'locality' => :'locality',
        :'organizational_units' => :'organizational-units',
        :'organizations' => :'organizations',
        :'postal_code' => :'postal-code',
        :'province' => :'province',
        :'public_key_pem_data' => :'public-key-pem-data',
        :'signing_method' => :'signing-method',
        :'street_address' => :'street-address',
        :'token' => :'token',
        :'ttl' => :'ttl',
        :'uid_token' => :'uid-token',
        :'uri_sans' => :'uri-sans',
        :'version' => :'version'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'common_name' => :'String',
        :'country' => :'String',
        :'display_id' => :'String',
        :'dns_names' => :'String',
        :'key_usage' => :'String',
        :'locality' => :'String',
        :'organizational_units' => :'String',
        :'organizations' => :'String',
        :'postal_code' => :'String',
        :'province' => :'String',
        :'public_key_pem_data' => :'String',
        :'signing_method' => :'String',
        :'street_address' => :'String',
        :'token' => :'String',
        :'ttl' => :'Integer',
        :'uid_token' => :'String',
        :'uri_sans' => :'String',
        :'version' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Akeyless::SignPKICertWithClassicKey` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Akeyless::SignPKICertWithClassicKey`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'common_name')
        self.common_name = attributes[:'common_name']
      end

      if attributes.key?(:'country')
        self.country = attributes[:'country']
      end

      if attributes.key?(:'display_id')
        self.display_id = attributes[:'display_id']
      end

      if attributes.key?(:'dns_names')
        self.dns_names = attributes[:'dns_names']
      end

      if attributes.key?(:'key_usage')
        self.key_usage = attributes[:'key_usage']
      else
        self.key_usage = 'DigitalSignature,KeyAgreement,KeyEncipherment'
      end

      if attributes.key?(:'locality')
        self.locality = attributes[:'locality']
      end

      if attributes.key?(:'organizational_units')
        self.organizational_units = attributes[:'organizational_units']
      end

      if attributes.key?(:'organizations')
        self.organizations = attributes[:'organizations']
      end

      if attributes.key?(:'postal_code')
        self.postal_code = attributes[:'postal_code']
      end

      if attributes.key?(:'province')
        self.province = attributes[:'province']
      end

      if attributes.key?(:'public_key_pem_data')
        self.public_key_pem_data = attributes[:'public_key_pem_data']
      end

      if attributes.key?(:'signing_method')
        self.signing_method = attributes[:'signing_method']
      end

      if attributes.key?(:'street_address')
        self.street_address = attributes[:'street_address']
      end

      if attributes.key?(:'token')
        self.token = attributes[:'token']
      end

      if attributes.key?(:'ttl')
        self.ttl = attributes[:'ttl']
      end

      if attributes.key?(:'uid_token')
        self.uid_token = attributes[:'uid_token']
      end

      if attributes.key?(:'uri_sans')
        self.uri_sans = attributes[:'uri_sans']
      end

      if attributes.key?(:'version')
        self.version = attributes[:'version']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @display_id.nil?
        invalid_properties.push('invalid value for "display_id", display_id cannot be nil.')
      end

      if @signing_method.nil?
        invalid_properties.push('invalid value for "signing_method", signing_method cannot be nil.')
      end

      if @ttl.nil?
        invalid_properties.push('invalid value for "ttl", ttl cannot be nil.')
      end

      if @version.nil?
        invalid_properties.push('invalid value for "version", version cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @display_id.nil?
      return false if @signing_method.nil?
      return false if @ttl.nil?
      return false if @version.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          common_name == o.common_name &&
          country == o.country &&
          display_id == o.display_id &&
          dns_names == o.dns_names &&
          key_usage == o.key_usage &&
          locality == o.locality &&
          organizational_units == o.organizational_units &&
          organizations == o.organizations &&
          postal_code == o.postal_code &&
          province == o.province &&
          public_key_pem_data == o.public_key_pem_data &&
          signing_method == o.signing_method &&
          street_address == o.street_address &&
          token == o.token &&
          ttl == o.ttl &&
          uid_token == o.uid_token &&
          uri_sans == o.uri_sans &&
          version == o.version
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [common_name, country, display_id, dns_names, key_usage, locality, organizational_units, organizations, postal_code, province, public_key_pem_data, signing_method, street_address, token, ttl, uid_token, uri_sans, version].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Akeyless.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
